config/routes.rb
SeatingChartApp::Application.routes.draw do

  resources :users
  resources :sessions,   only: [:new, :create, :destroy]
  resources :classrooms
  resources :tables
  resources :students

  root to: 'static_pages#home'
  
  match '/signup',        to: 'users#new'
  match '/signin',        to: 'sessions#new'
  match '/signout',       to: 'sessions#destroy', via: :delete
  match '/help',          to: 'static_pages#help'
  match '/about',         to: 'static_pages#about'
  match '/contact',       to: 'static_pages#contact'
  match '/newclassroom',  to: 'classrooms#new', as: :newclassroom
  
  match 'classrooms/:id/tables/display_form',           to: 'tables#display_form', as: :tables_display_form
  match 'classrooms/:id/addtables',                     to: 'tables#addtables', as: :addtables
  match 'classrooms/:id/students/display_form',         to: 'students#display_form', as: :students_display_form
  match 'classrooms/:id/addstudents',                   to: 'students#addstudents', as: :addstudents
  match 'classrooms/:id/students/display_form_pinned',  to: 'students#display_form_pinned', as: :display_form_pin
  match 'classrooms/:id/students/add_pin_table',        to: 'students#add_pin_table', as: :add_pin_table
  match 'classrooms/:id',                               to: 'classrooms#show', as: :display_classroom
  match 'classrooms/:id/results',                       to: 'classrooms#results', as: :results

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>
	This is an application that is designed to create a seating chart
	based on a user's input of variables such as number of tables,
	seats per table, and number of iterations of seat changes.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<address>
	Melissa Slaughter<br />
	Jackson, Wyoming<br />
	<a href="mailto:melissa.slaughter@journeysschool.org">
		melissa.slaughter@journeysschool.org</a><br />
</address>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<h3>
	This is the help page. Advice: good luck and figure it out for yourself!
</h3>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Seating Chart App</h1>
	
	<h2>
		The place to build seating charts for any and all situations
	</h2>
	
	<% if signed_in? %>
		<%= link_to "Create a Classroom", newclassroom_path, class: "btn btn-large btn-primary" %>
	<% else %>
		<%= link_to "Sign up here", signup_path, class: "btn btn-large btn-primary" %>
	<% end %>
	
	<p></p><br />
	
	<img src="/assets/notebook_01.png" width="150">
</div>