config/routes.rb
SeatingChartApp::Application.routes.draw do

  resources :users
  resources :sessions,   only: [:new, :create, :destroy]
  resources :classrooms
  resources :tables
  resources :students

  root to: 'static_pages#home'
  
  match '/signup',        to: 'users#new'
  match '/signin',        to: 'sessions#new'
  match '/signout',       to: 'sessions#destroy', via: :delete
  match '/help',          to: 'static_pages#help'
  match '/about',         to: 'static_pages#about'
  match '/contact',       to: 'static_pages#contact'
  match '/newclassroom',  to: 'classrooms#new', as: :newclassroom
  
  match 'classrooms/:id/tables/display_form',           to: 'tables#display_form', as: :tables_display_form
  match 'classrooms/:id/addtables',                     to: 'tables#addtables', as: :addtables
  match 'classrooms/:id/students/display_form',         to: 'students#display_form', as: :students_display_form
  match 'classrooms/:id/addstudents',                   to: 'students#addstudents', as: :addstudents
  match 'classrooms/:id/students/display_form_pinned',  to: 'students#display_form_pinned', as: :display_form_pin
  match 'classrooms/:id/students/add_pin_table',        to: 'students#add_pin_table', as: :add_pin_table
  match 'classrooms/:id',                               to: 'classrooms#show', as: :display_classroom
  match 'classrooms/:id/results',                       to: 'classrooms#results', as: :results

end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id                   :integer         not null, primary key
#  classroom_id         :integer
#  name                 :string(255)
#  pin                  :boolean         default(FALSE)
#  pinned_table         :integer
#  students_sat_next_to :string(255)
#  created_at           :datetime        not null
#  updated_at           :datetime        not null
#

class Student < ActiveRecord::Base
  attr_accessible :classroom_id, :name, :pin, :pinned_table
  
  belongs_to  :classroom
  
  before_save :default_values
  
  validates :name, presence: true
  validates :classroom_id, presence: true
  
  def default_values
    self.students_sat_next_to ||= ""
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_filter :signed_in_user
  
  def new
    @student = Student.new
  end
  
  def create
  end
  
  def display_form
  end
  
  def addstudents
    @classroom = Classroom.find(params[:id])
    (1..@classroom.num_students).each do |t|
      @classroom.students.build(params["student #{t}"])
    end
    if @classroom.save
      is_pin_path = false
      for student in @classroom.students
        if student.pin
          is_pin_path = true
          break
        end
      end
      if is_pin_path
        redirect_to display_form_pin_path(@classroom.id)
      else
        redirect_to results_path(@classroom.id)
      end
    else
      render 'new'
    end
  end
  
  def add_pin_table
    @classroom = Classroom.find(params[:id])
    for student in @classroom.students
      if student.pin
        pin_table = Integer(params["#{student.name}"])
        student[:pinned_table] = pin_table
        student.save
      end
    end
    if @classroom.save
      redirect_to results_path(@classroom.id)
    else
      render 'new'
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/display_form.html.erb
<% provide(:title, 'Build Classroom - Students') %>
<h1>Build Classroom - Students</h1>

<div class="row">
	<div class="span5 offset1">	
		<% @classroom = Classroom.find(params[:id]) %>
		<%= form_tag (addstudents_path method: 'post', id: params[:id]) do %>
		
			<% (1..@classroom.num_students).each do |t| %>
				<div class="span3 offset3">
					<%= check_box "student #{t}", "pin" %> pin this student
				</div>
				<%= text_field "student #{t}", "name", placeholder: "Student name..." %>
				
			
			<% end %>
			
			<%= submit_tag 'Submit' %>
			
		<% end %>
	</div>
</div>

app/views/students/display_form_pinned.html.erb
<% provide(:title, 'Build Classroom - Students') %>
<h1>Build Classroom - Students</h1>

<div class="row">
	<div class="span5 offset3">	
		<% @classroom = Classroom.find(params[:id]) %>
		<% tables = [] %>
		<% for table in @classroom.tables %>
			<% tables.push(table.name) %>
		<% end %>
		<%= form_tag (add_pin_table_path method: 'post', id: params[:id]) do %>
			<% for student in @classroom.students %>
				<% if student.pin %>
					<label><%= "Pin #{student.name} to which table?"%></label>
					<%= select_tag "#{student.name}", options_for_select(tables) %>
				<% end %>
			<% end %>
		<%= submit_tag 'Submit' %>
		<% end %>
	</div>
</div>

app/views/students/new.html.erb
<% provide(:title, 'Build Classroom => students') %>
<h1>Build Classroom</h1>