config/routes.rb
SeatingChartApp::Application.routes.draw do

  resources :users
  resources :sessions,   only: [:new, :create, :destroy]
  resources :classrooms
  resources :tables
  resources :students

  root to: 'static_pages#home'
  
  match '/signup',        to: 'users#new'
  match '/signin',        to: 'sessions#new'
  match '/signout',       to: 'sessions#destroy', via: :delete
  match '/help',          to: 'static_pages#help'
  match '/about',         to: 'static_pages#about'
  match '/contact',       to: 'static_pages#contact'
  match '/newclassroom',  to: 'classrooms#new', as: :newclassroom
  
  match 'classrooms/:id/tables/display_form',           to: 'tables#display_form', as: :tables_display_form
  match 'classrooms/:id/addtables',                     to: 'tables#addtables', as: :addtables
  match 'classrooms/:id/students/display_form',         to: 'students#display_form', as: :students_display_form
  match 'classrooms/:id/addstudents',                   to: 'students#addstudents', as: :addstudents
  match 'classrooms/:id/students/display_form_pinned',  to: 'students#display_form_pinned', as: :display_form_pin
  match 'classrooms/:id/students/add_pin_table',        to: 'students#add_pin_table', as: :add_pin_table
  match 'classrooms/:id',                               to: 'classrooms#show', as: :display_classroom
  match 'classrooms/:id/results',                       to: 'classrooms#results', as: :results

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_filter :signed_in_user
  
  def new
    @table = Table.new
  end
  
  def create
  end
  
  def display_form
  end
  
  def addtables
    @classroom = Classroom.find(params[:id])
    (1..@classroom.num_tables).each do |t|
      params_max_students = Integer(params["table #{t}"][:max_students])
      puts "Table #{t}: #{params_max_students}"
      @classroom.tables.build(name:t, max_students:params_max_students)
    end
    if @classroom.save
      redirect_to students_display_form_path(@classroom.id)
    else
      render 'new'
    end
  end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/display_form.html.erb
<% provide(:title, 'Build Classroom - Tables') %>
<h1>Build Classroom - Tables</h1>

<div class="row">
	<div class="span6 offset3">	
		<% @classroom = Classroom.find(params[:id]) %>
		<%= form_tag (addtables_path method: 'post', id: params[:id]) do %>
		
			<% (1..@classroom.num_tables).each do |t| %>
				
				<label><%= "Table #{t}" %></label>
				<%= text_field "table #{t}", "max_students", placeholder: "Max students..." %>
			
			<% end %>
			
			<%= submit_tag 'Submit' %>
			
		<% end %>
	</div>
</div>

app/views/tables/new.html.erb
<% provide(:title, 'Build Classroom - Tables') %>
<h1>Build Classroom - Tables</h1>